### ISSUE TITLE
Change bws python script for terraform

### ISSUE THREAD

**Issue by chkpwd** [chkpwd/iac#996]

**Comment by chkpwd** [comment]
Be able to reference secrets via a top level key in the yaml schema.

ns-security-secrets
```yaml
authentik:
  secret_key: 4YDtm1DI5WXUPKuCOzco5CSAovDAafRMvLQPIYlVbvdw4Tb6sR
  email_address: blah@gmail.com
  app_password: blah
  main_user_password: blah
cilium:
  secret_key: somekey
  other: key
```

Terraform: data.external.bws_lookup.result["authentik"]["bootstrap_token"]
